### ISSUE TITLE
clearer errors 

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/observatory-extension#106]
Most errors contain a lot of information about plproxy, like so:
![screen shot 2016-06-06 at 10 58 48](https://cloud.githubusercontent.com/assets/1041056/15826479/ad7d9470-2bd5-11e6-80d3-9883d3b1be8b.png)

Since these errors are reported to the user and they cannot act on them directly, it would be great to have clearer errors about what is happening.

**Comment by javitonino** [comment]
A lot of this has been improved by recent work on adding pre-check. Errors presented to the user should be friendlier now.
