### ISSUE TITLE
Dump version does not match with version in obs_dump_version

### ISSUE THREAD

**Issue by iriberri** [CartoDB/observatory-extension#140]
```
obs_2016_06_28_38328f72b7=# select * from observatory.obs_dump_version;
          dump_id           
----------------------------
 Dump_2016_06_22_ca7278576d
(1 row)
```

Wondering if this is controlled or if we're forgetting to update the `obs_dump_version` table somewhere. @talos any clue?

**Comment by talos** [comment]
Weird -- that's old enough that there may have still been a kink in the dump generation process resulting in no update.

I checked the latest DB and the rows are being inserted properly (you have to select `MAX`).  That means the next dump should work OK.

**Comment by iriberri** [comment]
Cool! As we're gonna release a new one I'm gonna forget about this :)
