### ISSUE TITLE
Public functions for Augmentation Usage methods

### ISSUE THREAD

**Issue by andrewxhill** [CartoDB/observatory-extension#16]
OBS_GetMeasure(Point Geometry, Measure ID);
 OBS_GetMeasure(Polygon Geometry, Measure ID);
 OBS_GetUSCensusMeasure(Address String, Simple name);
 OBS_GetUSCensusMeasure(Polygon Geometry, Simple name);

https://github.com/CartoDB/observatory-extension/issues/15

cc @talos @stuartlynn @ohasselblad

**Comment by talos** [comment]
These are all done in https://github.com/CartoDB/observatory-extension/tree/release_v1_api_functions_aug_use, along with:

```
OBS_GetCategory(Point Geometry, Category ID); => Text
OBS_GetCategory(Polygon Geometry, Category ID); => Text
OBS_GetUSCensusCategory(Point Geometry, Simple name); => Text
OBS_GetUSCensusCategory(Polygon Geometry, Simple Name); => Text
```
