### ISSUE TITLE
Add final versions of OBS_Search and OBS_GetAvailableBoundaries

### ISSUE THREAD

**Issue by andrewxhill** [CartoDB/observatory-extension#18]
OBS_Search(Search Term, Relevant Boundary);
 OBS_GetAvailableBoundaries(Relevant Geometry);

https://github.com/CartoDB/observatory-extension/issues/15

cc @stuartlynn @ohasselblad @talos

**Comment by stuartlynn** [comment]
Obs search should be added #19
