### ISSUE TITLE
Missing boundaries for Canary Islands

### ISSUE THREAD

**Issue by ernesmb** [CartoDB/observatory-extension#181]
When trying to get IGN boundary geometries for Canary Islands region in Spain, no rows are returned. 
### STR

Run a query of the type: 

```
SELECT OBS_GetBoundary(
   CDB_LatLng(27.983487,-15.569000),
   'es.cnig.prov'
 )
```

or 

```
SELECT OBS_GetBoundary(
   CDB_LatLng(27.983487,-15.569000),
   'es.cnig.muni'
 )
```

No results are returned. 
### Context
- Same queries return the expected geometries in other regions of peninsular Spain. 
- When using `es.ine.geoms`, it works as expected. It only fails with `cnig` geometries.
### Guess

ING data for the Canary Islands comes in a separate file, as it is projected in a different CRS than the rest of Spanish territory. Is it possible we didn't load it into the Observatory database?

cc/ @jsanz

**Comment by javitonino** [comment]
This should be solved now. The boundary queries return data, and the `.carto` returns a population of 368k, a little off the official value, but I feel that it is close enough.

Thanks for the detailed report!
