### ISSUE TITLE
Open source this repo

### ISSUE THREAD

**Issue by talos** [CartoDB/observatory-extension#251]
`observatory-extension` is a core component of the Observatory product, which we are now beginning to use independently with some clients.

It would make sense to open source it, so that it can be integrated into a package where someone can run ETL scripts and then test to make sure everything works using API functions from here.

This repo was never used to store any sensitive key information, so we should be safe to keep the commits.  The only semi-sensitive information I can think of is some references to S3 buckets on the PR deploys.

@rochoa I'd like your opinion on opening this up -- if we go through and redact any S3 bucket details (should be able to leave the has, which is the important part anyway) do you think there is anything else we should be concerned about?

**Comment by javisantana** [comment]
Vamos!
