### ISSUE TITLE
Missing obs_column_tag in fixtures

### ISSUE THREAD

**Issue by talos** [CartoDB/observatory-extension#26]
@ohasselblad Not sure the best way to get the dump through foreign data wrappers... neither `pg_dump -U postgres` nor with the cartodb user works.

**Comment by ohasselblad** [comment]
I'll prep it from a dump from `observatory`. should we did a fresh dump of the other metadata, too, or has that not changed since last friday?

**Comment by talos** [comment]
In this situation, it should be harmless to leave the other metadata alone.

**Comment by talos** [comment]
We got 'em!
