### ISSUE TITLE
GetAvailableGeometries should accept numgeoms parameters

### ISSUE THREAD

**Issue by javitonino** [CartoDB/observatory-extension#309]
`GetAvailableGeometries` does not take a numgeoms parameters, so when calculating geometry scores it defaults to 3k geometries. See:
https://github.com/CartoDB/observatory-extension/blob/develop/src/pg/sql/41_observatory_augmentation.sql#L143-L144
https://github.com/CartoDB/observatory-extension/blob/develop/src/pg/sql/42_observatory_exploration.sql#L541-L543

As a result, we tend to score the highest small-ish geometries, never suggesting high-level geos such as provinces/states.

This is specially relevant if we are going to do https://github.com/CartoDB/cartodb/issues/12623

**Comment by ethervoid** [comment]
This CRs includes two PRs: #313 and cartodb/dataservices-api#403

**Comment by ethervoid** [comment]
As a side note I've tested with change in builder to pass the new parameter, upgrading and downgrading the extension for client and server to check for compatibility and so on

**Comment by ethervoid** [comment]
### Acceptance

- Install the new version of the observatory extension
- Check everything works as intented with a new field
- Install the new version of the DS server
- Check again everything works find and check we have just one version of the function `obs_getavailablegeometries` in `cdb_dataservices_server`
- Install the client version of DS in your testing user
- Check again everything works find and check we have just one version of the function `obs_getavailablegeometries` in `cdb_dataservices_client`
- Make a call to the function passing different `number_geometries` parameter and check the scores are different
- Go back to the previous version in DS client and server and check the functions are the same as before.

**Comment by ethervoid** [comment]
Added changes to increase version in CartoDB: cartodb/cartodb#12942

**Comment by javitonino** [comment]
This will need a minor docs update @csobier (this is still not released). We are just adding an optional numeric parameter `number_geoms` to [`OBS_GetAvailableGeometries`](https://carto.com/docs/carto-engine/data/discovery-functions/#obsgetavailablegeometriesbounds-filtertags-numerid-denomid-timespan). The user can pass the number of geometries in his dataset in order to get back scores adjusted to the number of geometries and bounding box.

**Comment by csobier** [comment]
Great! Thanks for tagging me so I can track when this is released and ready for doc updates
