### ISSUE TITLE
Error: `schema "cdb_observatory" does not exist`

### ISSUE THREAD

**Issue by csobier** [CartoDB/observatory-extension#316]
Reported by @andy-esch , some of the code snippets have `cdb_observatory.<function_name>`, but carto throws errors `schema "cdb_observatory" does not exist`.

This seems to be specific to the **Discovery Functions** only. The other OBS functions don’t have that prefix?
- original code stored here: https://github.com/CartoDB/observatory-extension/blob/develop/doc/discovery_functions.md
- live docs pulling from this repo: https://carto.com/docs/carto-engine/data/discovery-functions/

@hannahblue, can you try to track when this change was implemented, and let me know what the new doc requirements are?

**Comment by hannahblue** [comment]
@ramiroaznar can the Response team look into this please?

cc @juanignaciosl

**Comment by ramiroaznar** [comment]
Which ones are returning that error?

**Comment by ramiroaznar** [comment]
I think this is not a RT task. DO team should take care of this. And then change the docs accordingly.

**Comment by javitonino** [comment]
We can just remove the `cdb_observatory` prefix from the docs, and that's it. Internally, that schema is used, but it should never have been present in the user-facing documentation.

**Comment by javitonino** [comment]
PR https://github.com/CartoDB/observatory-extension/pull/317
