### ISSUE TITLE
obs_getavailablegeometries and *numerators functions "do not exist" errors

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/observatory-extension#323]
I'm getting the following for `OBS_GetAvailableGeometries`:
```
REMOTE ERROR: function cdb_observatory.obs_getavailablegeometries(geometry, text[], text, text, text, integer) does not exist
```

I noticed it through other usage, but it's not even working from basic docs code snippets:
```
SELECT * FROM OBS_GetAvailableGeometries(
  ST_MakeEnvelope(-74, 41, -73, 40, 4326));
```

I've had the same problem in Builder and through the SQL API, both on team account and a separate user account (user `cartoframes`).

cc @antoniocarlon

**Comment by andy-esch** [comment]
Same errors are now happening over cartoframes' CI: https://travis-ci.org/CartoDB/cartoframes/jobs/322242189#L632-L634
This same test suite passed yesterday.

**Comment by antoniocarlon** [comment]
The problem was that the DO configuration for both `production` and `staging` in the `cdb_conf` table was incorrect.

The `dbname` entry in `data_observatory_conf` has to point to a DO database with the DO extension deployed on it. I have added more info about it in the internal documentation.

**Comment by andy-esch** [comment]
Thanks for the info, @antoniocarlon. Everything seems to be back to normal now.
