### ISSUE TITLE
Fix the 'holes' problem

### ISSUE THREAD

**Issue by antoniocarlon** [CartoDB/observatory-extension#335]
Fix the 'holes' problem (incorrectly generated MVT geometries) for certain zoom levels

**Comment by hannahblue** [comment]
@antoniocarlon this is done, right?

**Comment by antoniocarlon** [comment]
Yes, it should be done but I was waiting for the PostGIS MVT issue to be solved to recheck it.
We will notice if this arises again, so I'm closing it for now.
