### ISSUE TITLE
Avoid using CartoDB extension from Observatory extension

### ISSUE THREAD

**Issue by zenitraM** [CartoDB/observatory-extension#34]
It seems that the cartodb-postgresql extension is only used from: https://github.com/CartoDB/observatory-extension/blob/qlik-alfa-plproxy/src/pg/sql/40_observatory_utility.sql#L115.

Could we drop it to avoid dependency mayhem? 🙏 

cc @rafatower

**Comment by ohasselblad** [comment]
done in https://github.com/CartoDB/observatory-extension/pull/30/commits/11df52dc3b2ba7a5a3262c5d781658d7568321e2

**Comment by ohasselblad** [comment]
we don't do it anymore, closing :)
