### ISSUE TITLE
Return the parent id and name for a given geometry

### ISSUE THREAD

**Issue by antoniocarlon** [CartoDB/observatory-extension#340]
Return the parent id and name for a given geometry (in the `OBS_GetMCDOMVT` or in the `xyz` table generation??)

**Comment by juanignaciosl** [comment]
Related: CartoDB/Geographica-Product-Coordination/issues/14#issuecomment-415531543

**Comment by juanignaciosl** [comment]
We have to add the parent names in a semantic way:

```
id: '120570051011032'
block_id: '120570051011032'
block_group_id: '120570051011'
county: 'Hillsborough'
state: 'Florida'
...
median_age 27.5
total_pop 317
```

**Comment by javitonino** [comment]
How does point on surface reconcile with multiple parents of the same level? This happens with non-hierarchical geometries (IIRC we have some of those).

If you intersect a single point from the child, you are going to only get one parent (assuming a non-overlapping topology). In order to get all parents, you'd need to do a polygon-to-polygon intersection (much slower, I know).

**Comment by antoniocarlon** [comment]
True, we will need to perform heavy polygon to polygon intersections in those cases. Fortunately, we know them and we can limit those heavy intersections to the non coupled layers, keeping the point on surface approach for the rest

**Comment by juanignaciosl** [comment]
> How does point on surface reconcile with multiple parents of the same level? This happens with non-hierarchical geometries (IIRC we have some of those).
...
> we know them and we can limit those heavy intersections to the non coupled layers

Which are the geometries where point in polygon is not enough?

**Comment by antoniocarlon** [comment]
Those where the layer and its parent are not coupled (a feature can have several parents). In US, I think that we won't find this case (except for zipcodes, maybe, I'm not sure)

**Comment by juanignaciosl** [comment]
ETL: CartoDB/bigmetadata/pull/572
Tiler: CartoDB/do_tiler/pull/38

**Comment by juanignaciosl** [comment]
Deployed for US.
