### ISSUE TITLE
Create Point Radius methods of the OBS_GetBoundariesByBBox methods

### ISSUE THREAD

**Issue by andrewxhill** [CartoDB/observatory-extension#37]

**Comment by ohasselblad** [comment]
Work here: https://github.com/CartoDB/observatory-extension/commit/0ba66c8f31042bc66a502efbaf8b99e71984e90d

**Comment by andrewxhill** [comment]
@ohasselblad could you put in placeholder Headers and TODO lines for the couple of functions you included? 

https://github.com/CartoDB/observatory-extension/blob/develop/doc/methods.md

**Comment by ohasselblad** [comment]
See here: https://github.com/CartoDB/observatory-extension/blob/develop/doc/methods.md#obs_getboundariesbygeometrygeometry-geometry_id

**Comment by andrewxhill** [comment]
oop, killer!

On Wed, May 4, 2016 at 1:16 PM, Andy Eschbacher <notifications@github.com>
wrote:

> See here:
> https://github.com/CartoDB/observatory-extension/blob/develop/doc/methods.md#obs_getboundariesbygeometrygeometry-geometry_id
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/observatory-extension/issues/37#issuecomment-216936653>
>



-- 

andrewxhill <http://twitter.com/andrewxhill>
http://cartodb.com
