### ISSUE TITLE
load fixtures before running tests

### ISSUE THREAD

**Issue by ohasselblad** [CartoDB/observatory-extension#5]
Based on patterns in crankshaft, we loaded fixtures by doing `\i test/fixtures/obs_table.sql` in the test script. The drawback of this is that psql outputs hundreds of insert statements that then have to show up in the expected tests.

@rafatower, could we have a separate step in the makefile which loads the tables before we run the test so that the amount of information in the expected out is minimized to the results we are looking for?

**Comment by rafatower** [comment]
I'll look into it. Maybe the solution is not to split into different phases but just silence the output from the set up phase in the tests (pretty standard)
