### ISSUE TITLE
DB dump needed for the v1 release

### ISSUE THREAD

**Issue by rafatower** [CartoDB/observatory-extension#59]
Hey,

This ticket is created for tracking purposes only. We'd need to have the db dump to be used with the currrent version of the extension, as agreed in the "Data Observatory Deployment and Release Process" doc.

Along with it there should be a set of defined monitoring and performance checks.

We'd need such dump to integrate and exercise the deployment process, even if it is not the very final one yet.

cc/ @andrewxhill @javisantana @CartoDB/dataservices

**Comment by talos** [comment]
@rafatower I've posted a link to the dump on the #dataservices slack.

RE performance/monitoring checks, we should check in about those tomorrow morning.  I'm working on an automated suite now, but it would require Python to run and I need to make sure we're on the same page about the environment it will be running in and how it will be configured.
