### ISSUE TITLE
geometry id type differences

### ISSUE THREAD

**Issue by ohasselblad** [CartoDB/observatory-extension#66]
@talos Right now who's on first has a numeric type id (wof_id) while us census has a text type id (geoid). This is causing problems when returning values from the tables that contain this information. I can get around it by casting in the queries that output the data, but thought that stronger constraints on the data might be a more effective way to move forward.

**Comment by talos** [comment]
We should talk about this tomorrow, but I can definitely say casting to `TEXT` will cause us no problems right now.

Personally, I think going forward it won't cause any issues either -- if we ingest data we could choose to cast it to `TEXT` ourselves, but ID comparison should always be by equality.
