### ISSUE TITLE
Add missing measure_names in the Glossary

### ISSUE THREAD

**Issue by csobier** [CartoDB/observatory-extension#72]
For public Docs, add [missing Glossary descriptions](http://768-add-data-observatory-section.docs.cartodb-staging.com/cartodb-platform/dataobservatory/glossary/#obsgetuscensusmeasure-names-table) for the measure_tables:
https://github.com/CartoDB/observatory-extension/pull/40#issuecomment-216224393

@talos

**Comment by andrewxhill** [comment]
This is complete. Just pushed it. @makella is taking a look at the language too. But good enough to close now.
