### ISSUE TITLE
Something weird with the OBS_GetUSCensusCategory

### ISSUE THREAD

**Issue by ethervoid** [CartoDB/observatory-extension#83]
This query was working at this [commit](https://github.com/CartoDB/observatory-extension/commit/f17dc6d8ff2ec1d1ea36d1ea278768ba665ad165):

```
SELECT OBS_GetUSCensusCategory('0103000020E61000000100000021000000BB366F6D917B52C0E7BB6EA82B5A444067224C85937B52C0810205E70E5A4440596D6342997B52C09BED2952F35944400A96386CA27B52C07B6D31F9D95944402B81A0A8AE7B52C0D16B73D5C3594440C34C397FBD7B52C0D8B5B7C0B1594440CFD90A5ECE7B52C0BE8DD86CA45944405C7E229FE07B52C0A904EE5C9C59444017C1F28EF37B52C05E2745E099594440AE8A3873067C52C0FD62540F9D5944402F272292187C52C05502CBCAA5594440C3F17139297C52C0B3FBC4BCB3594440DDAE56C5377C52C00C46175CC6594440E96AB6A6437C52C0355C94F1DC5944402313AE684C7C52C05340159FF6594440B3B90FB5517C52C031F30168125A44407F43B357537C52C0DF95053B2F5A444059C17840517C52C0D9E08EFC4B5A44406580E8834B7C52C046B5B591675A444035736A5A427C52C0AF9A1AEB805A44402E721C1E367C52C0D226550F975A4440506D5C47277C52C0A2968A24A95A4440507C2868167C52C0D51FCE78B65A4440C4438226047C52C02369F888BE5A4440C9F10C36F17B52C027B1B205C15A4440AABE2451DE7B52C0F5E383D6BD5A44402A18B431CC7B52C01785C11AB55A444018320D8ABB7B52C070265B28A75A4440E28A0EFEAC7B52C09E518C88945A44401D08D61CA17B52C09E8195F27D5A4440D7C3405B987B52C0643CB044645A444047B16D0F937B52C04EC9837B485A4440BB366F6D917B52C0E7BB6EA82B5A4440'::geometry, 'Spielman-Singleton Segments: 10 Clusters') as category;
```

But right now after freezing branch at this [commit](https://github.com/CartoDB/observatory-extension/commit/8d17375766e78483eb5c6f3109418bc5a767cfff) , is returning NULL

<img width="1141" alt="captura de pantalla 2016-05-17 18 07 56" src="https://cloud.githubusercontent.com/assets/741240/15329882/b2edbeba-1c5a-11e6-8b3d-52d33f41cc97.png">

@talos @ohasselblad

**Comment by talos** [comment]
Looking into it.  Where are you running the query?

**Comment by ohasselblad** [comment]
with the version in team account i get `Low income, mix of minorities` for the category

**Comment by talos** [comment]
This was resolved as an issue with a mismatch between newer functions and older meta/data.  Were the new meta/data and functions deployed yet?

**Comment by ethervoid** [comment]
Yes, it's solved. Closing
